# Generated by Django 3.2.16 on 2023-10-29 12:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('birthday', '0003_congratualtion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Congratualtion',
            new_name='Congratulation',
        ),
    ]
